[package]
name = "pytools-rs"
version = "0.1.0"
edition = "2021"
authors = ["Kaushik Kulkarni <kaushikcfd@gmail.com>"]

[lib]
name = "pytools_rs"
path = "src/lib.rs"

[dependencies]
lazy_static = "1.4.0"
regex = "1.6.0"
